### ISSUE TITLE
uninitialized constant Yajl::Encoder

### ISSUE THREAD

**Issue by matthewmodestino** [cmeerbeek/fluent-plugin-splunkhec#14]
Hey Coen, 

Plugin ran great all day today with the new buffer settings, so I went to create my final cleaned up docker image this afternoon, and since then, have been unable to start my containers due to an error in fluentd/ruby:

```
2017-10-21 00:54:41 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
/var/lib/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/json_gem/encoding.rb:5:in `<top (required)>': uninitialized constant Yajl::Encoder (NameError)
Did you mean?  EncodingError
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/json_gem.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.4/lib/fluent/plugin/out_splunkhec.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/plugin.rb:104:in `new_output'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:128:in `add_match'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:72:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:64:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:64:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/root_agent.rb:112:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:770:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:553:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:571:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'
```

Not sure where this came from, I had no issues till rebuilding my image, but in the fluentd slack chat @repeatedly had this to say:

"fluent-plugin-splunkhec depends on yajl library but I assume this should be yajl-ruby
yajl gem is not for yajl json parser and yajl/yajl-ruby uses same file name. 
I think this conflict causes above error."
....
"For workaround, uninstall yajl gem, not yajl-ruby, at building image phase after installed splunkhec plugin"

I @ you in the chat so you could see. Not that familiar with Ruby so any help would be appreciated!

**Comment by matthewmodestino** [comment]
ah went back to fluentd v12.40 and am back up. :

```
 && echo 'gem: --no-document' >> /etc/gemrc \
 && gem install oj -v 2.18.3 \
 && gem install json -v 2.1.0 \
 && gem install fluentd -v 0.12.40 \
 && gem install fluent-plugin-record-reformer \
 && gem install fluent-plugin-splunkhec \
 && gem install fluent-plugin-kubernetes_metadata_filter \
 && gem install ffi \
 && gem install fluent-plugin-systemd -v 0.0.8 \

```

It must have been something with fluentd -v v0.14.22.rc1, which I tried to flipped to

**Comment by cmeerbeek** [comment]
Closed by PR @nchaugen
