### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by manuel220x** [cmeerbeek/fluent-plugin-splunkhec#18]
When the option "usejson = false " is used, then I get the error:

```
2018-01-12 15:38:10 -0800 [warn]: fluent/output.rb:381:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2018-01-12 15:38:11 -0800 error_class="NoMethodError" error="undefined method `+' for nil:NilClass" plugin_id="object:137e424"
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.5/lib/fluent/plugin/out_splunkhec.rb:77:in `block in write'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin/buf_memory.rb:67:in `feed_each'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/plugin/buf_memory.rb:67:in `msgpack_each'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.5/lib/fluent/plugin/out_splunkhec.rb:58:in `write'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/buffer.rb:333:in `pop'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/output.rb:342:in `try_flush'
  2018-01-12 15:38:10 -0800 [warn]: /var/lib/gems/2.3.0/gems/fluentd-0.12.42/lib/fluent/output.rb:149:in `run'
```

I tried on fluentd 0.12 and 0.14

**Comment by cmeerbeek** [comment]
Hi Manuel,

Can you run fluentd in debug and sent the output to me?

-----------------------

Coen Meerbeek

Social Networks: @cmeerbeek
Skype / IM: cmeerbeek
Mobile: +316 250 217 66

"In the Modern Meeting, the decision is King. All hail the King!"
