### ISSUE TITLE
Fails to submit to Splunk

### ISSUE THREAD

**Issue by HubDevUser** [cmeerbeek/fluent-plugin-splunkhec#24]
2018-07-01 22:39:04 +0000 [debug]: #0 Sending 305313 bytes to Splunk.
2018-07-01 22:39:10 +0000 [debug]: #0 Received new chunk, size=1186
2018-07-01 22:39:16 +0000 [debug]: #0 Received new chunk, size=19231
2018-07-01 22:40:04 +0000 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::SplunkHecOutput title=:"hec_worker_https://MyCloudInstance.cloud.splunk.com:8088/services/collector" error_class=Net::OpenTimeout error="execution expired"
2018-07-01 22:40:04 +0000 [error]: #0 unexpected error error_class=Net::OpenTimeout error="execution expired"
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `open'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/lib/ruby/2.5.0/net/http.rb:915:in `start'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:692:in `start'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:622:in `connection_for'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:927:in `request'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.0/lib/fluent/plugin/out_splunk_hec.rb:343:in `send_to_hec'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.0/lib/fluent/plugin/out_splunk_hec.rb:311:in `block in start_worker_threads'
  2018-07-01 22:40:04 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
#&lt;Thread:0x00007f0b0f5c91f0@/usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:70 run&gt; terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/2.5.0/net/http.rb:937:in `initialize': execution expired (Net::OpenTimeout)
    from /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `open'
    from /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
    from /usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
    from /usr/local/lib/ruby/2.5.0/net/http.rb:935:in `connect'
    from /usr/local/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
    from /usr/local/lib/ruby/2.5.0/net/http.rb:915:in `start'
    from /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:692:in `start'
    from /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:622:in `connection_for'
    from /usr/local/bundle/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:927:in `request'
    from /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.0/lib/fluent/plugin/out_splunk_hec.rb:343:in `send_to_hec'
    from /usr/local/bundle/gems/fluent-plugin-splunk-hec-1.0.0/lib/fluent/plugin/out_splunk_hec.rb:311:in `block in start_worker_threads'
    from /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-07-01 22:40:04 +0000 [info]: fluent/log.rb:322:info: Worker 0 finished unexpectedly with status 1

**Comment by HubDevUser** [comment]
using 443 addresses the issue since 8088 is no longer the default
